### ISSUE TITLE
SSL for Regression

### ISSUE THREAD

**Issue by xunzhaozhenli** [jkrijthe/RSSL#11]
Hi, thanks for developing such a great package!
Just wanna check, does SSL support regression problem?
I found few packages in R or Python can be used for regression. Perhaps SSL is more suitable for classification problem?

**Comment by jkrijthe** [comment]
Thanks! Indeed, the package focusses on classification problems, and does not contain methods for regression (although some of the implementations in the package could be adapted to this setting).

**Comment by xunzhaozhenli** [comment]
Thanks for your clarification @jkrijthe
