### ISSUE TITLE
Is 'Class Mass Normalisaiton' correctly specified in GRFClassier()?

### ISSUE THREAD

**Issue by liamnz** [jkrijthe/RSSL#15]
Hi @jkrijthe, thanks for putting this package together, its helped me learn a lot about semi-supervised learning 😃

At [line 49 in the GRFClassier()](https://github.com/jkrijthe/RSSL/blob/master/R/GRFClassifier.R#L49) code there is a switch to assign class labels based on the raw values from the harmonic function OR from the 'class mass normalised' values, but it appears the options are the wrong way around.

For example, should this
```
if (class_mass_normalization) {
  class_ind <- which_rowMax(responsibilities)
} else {
  class_ind <- which_rowMax(harmonic_f$fu_cmn)
}
```

look like this instead?

```
if (class_mass_normalization) {
  class_ind <- which_rowMax(harmonic_f$fu_cmn)
} else {
  class_ind <- which_rowMax(responsibilities)
}
```

**Comment by jkrijthe** [comment]
Thanks for opening this issue. I think you are correct: this seems to be the wrong way around! I hope to have a closer look if I'm not overlooking something soon, or otherwise fix it.
