### ISSUE TITLE
Publication?

### ISSUE THREAD

**Issue by andrewcstewart** [jkrijthe/RSSL#2]
Hi there.  I've been checking out your package and it's very nice.  I was wondering if you have an associated publication discussing the library / methods?  Also is there other documentation beyond the R package docs and the vignette linked from the main page?  Just curious.

Thanks!

**Comment by jkrijthe** [comment]
Thank you for checking out the package! I'm currently working on some bigger changes to the code that hopefully make the package easier to use and more consistent. I'm hoping to update the vignette and docs when the interfaces to the functions are more stable, to make them more complete.

As for the reference, there is currently no paper about the package itself, but I'm planning to write it at some point in the future. Mostly I think it would be nice to refer to it by the package name and the original paper about the method you are using. For the "Implicitly Constrained" methods in the package, this currently means referring to the preprint of the paper "Implicitly Constrained Semi-Supervised Least Squares Classification" by Jesse H. Krijthe and Marco Loog, which you can find on my website.

I will keep this issue open for now, until I come up with a better way to refer to the package.

**Comment by jkrijthe** [comment]
This has been documented now, both in the readme and when using citation("RSSL"). Thanks for the suggestion!
