### ISSUE TITLE
Installation Issue:

### ISSUE THREAD

**Issue by jamescfli** [jkrijthe/RSSL#3]
Hi jkrijthe,

I found the following message whne install RSSL through github. Do you have any clue on how to solve this issue? Thanks in advance.

> library(devtools)
> install_github("jkrijthe/RSSL")
> Downloading GitHub repo jkrijthe/RSSL@master
> Installing RSSL
> Skipping 9 packages not available: dplyr, ggplot2, kernlab, quadprog, Rcpp, RcppArmadillo, reshape2, scales, tidyr
> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
>   '/private/var/folders/w6/7k93kx3d2t57mj7vfh7f8v9w0000gn/T/RtmpZX2e5J/devtools2d7e77329b6b/jkrijthe-RSSL-a25af9e'  \
>   --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library' --install-tests 

\* installing _source_ package ‘RSSL’ ...
** libs
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/RcppArmadillo/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c GRFClassifier.cpp -o GRFClassifier.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/RcppArmadillo/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/RcppArmadillo/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c ssl.cpp -o ssl.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/RcppArmadillo/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c svmlin_rcpp.cpp -o svmlin_rcpp.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o RSSL.so GRFClassifier.o RcppExports.o ssl.o svmlin_rcpp.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2 -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [RSSL.so] Error 1
ERROR: compilation failed for package ‘RSSL’
- removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/RSSL’
  ERROR: Command failed (1)

**Comment by jkrijthe** [comment]
Did you install gfortran from https://cran.r-project.org/bin/macosx/tools/ ?

**Comment by jkrijthe** [comment]
Did you resolve the issue?

**Comment by dahliasan** [comment]
Hi I had a similar problem and followed this link which fixed it! 
http://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/
