### ISSUE TITLE
Problem with EMLinearDiscriminantClassifier

### ISSUE THREAD

**Issue by EliHei** [jkrijthe/RSSL#5]
Hi,

I guess that there is a problem with the function `EMLinearDiscriminantClassifier`. Using it, I get 
`Error in while (abs(logmarginal - logmarginal_old) > eps) { : 
  missing value where TRUE/FALSE needed`
which I thinks is due to the following code chunk:
```
logmarginal_old<-Inf
    logmarginal <- losspart(g_iteration,Xe,Ye) #losslogsum(g_iteration,X,Y,X_u,responsibilities)
#     print(logmarginal)
    while (abs(logmarginal-logmarginal_old) > eps)
```
Am I right?

**Comment by jkrijthe** [comment]
Yes, and I would expect the problem to start in the losspart function. Do you have an example dataset that you can share where the error occurs?

**Comment by jkrijthe** [comment]
Without a reproducible example, this issue is hard to fix.
