### ISSUE TITLE
Question about category variables

### ISSUE THREAD

**Issue by liuhyhit** [jkrijthe/RSSL#7]
Hi,

I'm new to this package and have 2 questions related to it:

1. Is there any function in this package is able to deal with category variable? I tried some, but all gave an error: Error in storage.mode(from) <- "double" :   (list) object cannot be coerced to type 'double'

2. Is there any function can deal with more than 2 classes? I notice that all sample data used in examples only have 2 classes.

Thanks.

**Comment by jkrijthe** [comment]
Hi,

1. Categories should be fine for most of the methods in the package. I guess this can be used in two ways: as long as the categorical variable is in your input dataframe as a factor and you use the formula interface it should work or you could explicitly convert the factors to numeric using, for instance, model.matrix. For your error, I'm not sure what is going on without seeing a more worked out example, but it seems the categorical variable is in the data.frame as a list?

2. In principal, many of the implemented methods can deal with multiple classes, but I have only implemented this in a small fraction. I guess LeastSquaresClassifier, ICLeastSquaresClassifier, LinearDiscriminantClassifier, MCLinearDiscriminantClassifier, GRFClassifier and probably SelfLearning can be applied to multi-class problems. For most of the others, you would first have to convert your multi-class problem into multiple binary decision problems.

Hope this helps.
