### ISSUE TITLE
Confusion about ?LearningCurveSSL

### ISSUE THREAD

**Issue by 2533245542** [jkrijthe/RSSL#8]
I am not sure if I understand it correctly but in the sentence below, should `type="unlabeled" ` be changed to `type="fraction" `. Please correct me if I am wrong. Thanks!

`If type="unlabeled" the total number of objects remains fixed, while the fraction of labeled objects is changed. frac sets the fractions of labeled objects that should be considered`

**Comment by jkrijthe** [comment]
You are right. Thanks! I updated the documentation.

**Comment by 2533245542** [comment]
I am sure this is a very basic question so I will just ask here; is the “time” measure from the result of LearningCurveSSL the time it takes to finish each iteration?

**Comment by jkrijthe** [comment]
Indeed, the time measures the number of seconds it takes to train a classifier (in that iteration). Note it only includes the time used for training, not, for instance, for generating predictions or other things that need to be evaluated for the different measures that you can supply to the LearningCurveSSL function. Hope this helps.
