### ISSUE TITLE
Confusion about bias in laplaciansvm

### ISSUE THREAD

**Issue by sonpro1296** [jkrijthe/RSSL#9]
Hi, 
I am trying to figure out how lapsvm works via code, and your package helps me a lot.
I am a little confused about how you choose the bias, can you explain it for me?
Many thanks.

**Comment by jkrijthe** [comment]
I see the code in that part is a bit of a mess, after trying different things to estimate the bias term in a stable way... Anyway, the idea is to consider the decision values for the support vectors, for we know by definition that they are at distance -1 or +1 from the decision boundary (depending which side of the decision boundary they are on). The bias is then the value that makes the decision values for the support vector attain the values -1 and +1.

If you have other ways of finding the bias that might work better, please let me know.
